# name: Deploy to staging
# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy_:
#     name: Deploying the frontend to staging
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout the code
#         uses: actions/checkout@v2

#       - name: executing remote ssh commands using sshkey
