name: Deploy to staging
on:
  push:
    branches:
      - main

jobs:
  deploy_:
    name: Deploying the frontend to staging
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and Deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY_DEV_SERVER }}
          EC2_HOST: ${{ secrets.EC2_DEV_SERVER_HOST }}
          EC2_USER: ${{ secrets.EC2_DEV_SERVER_USER}}
        run: |
          # Setup SSH key
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << 'EOF'
             cd CICDTutorial-2/
             git pull origin main
             pnpm install
             pnpm run build
             pm2 restart all
          EOF
          # Cleanup
          rm -f private_key.pem
