name: CI Pipeline for ExcalidrawClone

on:
  push:
    branches:
      - main

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build
