name: CI pipeline on push to main

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Setup ENV variables
        run: |
          cd packages/db
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Generate Prisma client
        run: |
          cd packages/db
          npx prisma migrate dev
          npx prisma generate

      - name: Build the project
        run: pnpm run build

        ##Build docker image
      - name: Build Docker Image
        run: |
          pwd
          docker build \
          -t edclone:latest \
          -t edclone:${{ github.ref_name }}-${{ github.sha }} \
          -t edclone:$(date +%Y%m%d-%H%M%S) \
          .
      - name: Push Docker Image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag edclone:latest edclone:${{ github.ref_name }}-${{ github.sha }} edclone:$(date +%Y%m%d%-%H%M%S)
          docker push Shikhar0895/edclone:latest
